volumes:
  db:
    name: mpt-db
networks:
  zenshi:
    name: zenshi-vps_default
    external: true
services:
  updater:
    container_name: mpt-updater
    command: bun run updater.js
    mem_limit: 1g
    restart: unless-stopped
    build:
      context: .
    environment:
      R2_BUCKET_NAME: mpt-stashes-prod
      poe_client_id: ${poe_client_id}
      poe_client_secret: ${poe_client_secret}
      CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      CLOUDFLARE_R2_KEY_ID: ${CLOUDFLARE_R2_KEY_ID}
      CLOUDFLARE_R2_KEY_SECRET: ${CLOUDFLARE_R2_KEY_SECRET}
      AWS_REGION: ${AWS_REGION}
      NODE_ENV: production
    volumes:
      - type: volume
        source: db
        target: /home/bun/app/db
    logging:
      driver: local
  scrapper:
    container_name: mpt-scrapper
    command: bun run scrapper.js
    mem_limit: 512m
    restart: unless-stopped
    build:
      context: .
    environment:
      R2_BUCKET_NAME: mpt-stashes-prod
      poe_client_id: ${poe_client_id}
      poe_client_secret: ${poe_client_secret}
      CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      CLOUDFLARE_R2_KEY_ID: ${CLOUDFLARE_R2_KEY_ID}
      CLOUDFLARE_R2_KEY_SECRET: ${CLOUDFLARE_R2_KEY_SECRET}
      AWS_REGION: ${AWS_REGION}
      NODE_ENV: production
    volumes:
      - type: volume
        source: db
        target: /home/bun/app/db
    logging:
      driver: local
  studio:
    container_name: mpt-studio
    image: coleifer/sqlite-web
    command: sqlite_web --host 0.0.0.0 --port 8082 /data/mpt.db
    environment:
      NODE_ENV: production
    ports:
      - 8082:8082
    volumes:
      - type: volume
        source: db
        target: /data
    restart: unless-stopped
    logging:
      driver: local
    networks:
      - zenshi
  webapp:
    container_name: mpt-app
    build:
      context: .
    command: bun run api.js
    environment:
      PORT: 4000
      NODE_ENV: production
    ports:
      - 4000:4000
    volumes:
      - type: volume
        source: db
        target: /home/bun/app/db
    restart: unless-stopped
    logging:
      driver: local
    networks:
      - zenshi
